apiVersion: v1
kind: DeploymentConfig
metadata:
  name: spring-boot-rest-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spring-boot-rest-example
    spec:
      containers:
      - image: rcastillejo/spring-boot-rest-example:7
        name: spring-boot-rest-example
        ports: 
        - containerPort: 8090 
